'use client'

import Link from 'next/link'
import { useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { ArrowDownRight, ArrowUpRight, Mail, Plus } from 'lucide-react'
import { projects } from '@/lib/site-data'

const capabilities = [
  { number: '01', title: 'Creative', short: 'Branding · Design · Photography · Video', text: 'Ideas with a point of view — made to give brands a distinct presence.', tone: 'bg-primary' },
  { number: '02', title: 'Digital & Technology', short: 'Web · Software · AI · Automation', text: 'Useful digital systems that make ambitious businesses easier to experience and operate.', tone: 'bg-secondary' },
  { number: '03', title: 'AV & Live Experiences', short: 'Sound · Visuals · Streaming · Technical Production', text: 'The technical and visual layer that turns a moment into an experience.', tone: 'bg-accent' },
  { number: '04', title: 'Production', short: 'Events · Conferences · Live Experiences', text: 'From first cue to final delivery, we make the idea happen in the real world.', tone: 'bg-blue-300' },
]

const process = [
  ['01', 'Discover', 'Understand the challenge.'],
  ['02', 'Create', 'Develop the concept.'],
  ['03', 'Build', 'Turn ideas into working solutions.'],
  ['04', 'Produce', 'Bring the experience to life.'],
]

export function HomeHero() {
  return (
    <section id="home" className="relative flex min-h-[100svh] overflow-hidden border-b border-white/10 bg-[#0c0b10] px-[clamp(32px,5vw,80px)] pb-8 pt-20 text-white sm:pb-12 sm:pt-24">
      <div className="pointer-events-none absolute inset-0 overflow-hidden">
        <div className="absolute -left-32 top-1/3 h-[32rem] w-[32rem] rounded-full bg-primary/10 blur-[140px]" />
        <div className="absolute right-[-10rem] top-[-8rem] h-[28rem] w-[28rem] rounded-full bg-secondary/10 blur-[150px]" />
        <div className="absolute bottom-[-12rem] right-1/4 h-[26rem] w-[26rem] rounded-full bg-accent/10 blur-[150px]" />
        <div className="absolute inset-0 opacity-25 [background-image:linear-gradient(rgba(255,255,255,.035)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,.035)_1px,transparent_1px)] [background-size:72px_72px]" />
      </div>
      <div className="relative mx-auto flex w-full max-w-[1500px] flex-col justify-between">
        <div>
          <div className="mb-6 flex items-center gap-4 sm:mb-8"><span className="h-px w-12 bg-primary" /><span className="font-mono text-[10px] uppercase tracking-[.26em] text-white/45">A Creative Technology &amp; Experiences Company</span></div>
          <motion.h1 initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8, ease: 'easeOut' }} className="max-w-[1100px] font-display text-[clamp(3.6rem,6.8vw,8rem)] font-bold leading-[.82] tracking-[-.075em]">
            <span className="block">We don&apos;t just</span>
            <span className="block">build brands.</span>
            <span className="block text-white/45">We create</span>
            <span className="text-gradient block" style={{ backgroundImage: 'var(--brand-gradient)' }}>experiences.</span>
          </motion.h1>
          <div className="mt-4 max-w-[590px] sm:mt-6"><p className="text-sm leading-7 text-white/55 sm:text-base">VisionVerve is a Creative Technology &amp; Experiences Company combining creativity, digital technology, audiovisual production and event production to bring ambitious ideas to life.</p><div className="mt-7 flex flex-wrap gap-7"><Link href="#contact" className="group inline-flex items-center gap-2 text-sm font-semibold">Start a project <ArrowUpRight className="h-4 w-4 text-primary transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" /></Link><Link href="#work" className="inline-flex items-center gap-2 text-sm text-white/55 transition-colors hover:text-white">See selected work <ArrowDownRight className="h-4 w-4" /></Link></div></div>
        </div>
        <div className="mt-16 flex items-end justify-between gap-6 font-mono text-[10px] uppercase tracking-[.22em] text-white/40 sm:mt-20"><span>Creative / Technology / AV / Production</span><span className="text-right">Cape Town, ZA</span></div>
      </div>
    </section>
  )
}

export function CapabilityExperience() {
  const [open, setOpen] = useState(0)
  return <section id="divisions" className="border-b border-border py-24 sm:py-32"><div id="capabilities" className="mx-auto max-w-[1500px] scroll-mt-20 px-4 sm:px-8 lg:px-12"><div className="mb-14 max-w-2xl"><p className="mb-4 font-mono text-[10px] uppercase tracking-[.3em] text-primary">02 / The system</p><h2 className="font-display text-4xl font-semibold tracking-tight sm:text-7xl">One company.<br /><span className="text-foreground/40">Four disciplines.</span></h2><p className="mt-6 max-w-md text-sm leading-7 text-muted-foreground">Creative, technology, AV and production are connected here. Change the discipline to see how we think.</p></div><div className="grid gap-10 md:grid-cols-[.9fr_1.1fr] md:items-start"><div className="divide-y divide-border border-y border-border">{capabilities.map((item, i) => { const active = open === i; return <div key={item.number}><button type="button" aria-expanded={active} onClick={() => setOpen(active ? -1 : i)} className="group grid w-full grid-cols-[2.5rem_1fr_auto] items-center gap-3 py-6 text-left sm:grid-cols-[4rem_1fr_auto] sm:py-8"><span className="font-mono text-xs text-primary">{item.number}</span><span className="font-display text-xl font-semibold transition-colors group-hover:text-primary sm:text-3xl">{item.title}</span><span className={`grid h-8 w-8 place-items-center border border-border transition-all ${active ? 'rotate-45 border-primary bg-primary text-primary-foreground' : ''}`}><Plus className="h-4 w-4" /></span></button><AnimatePresence initial={false}><motion.div initial={{ height: 0, opacity: 0 }} animate={active ? { height: 'auto', opacity: 1 } : { height: 0, opacity: 0 }} className="overflow-hidden"><div className="pb-7 pl-10 sm:pl-16"><p className="text-xs uppercase tracking-[.16em] text-muted-foreground">{item.short}</p><p className="mt-3 max-w-md text-sm leading-7 text-muted-foreground">{item.text}</p></div></motion.div></AnimatePresence></div> })}</div><div className="relative min-h-[300px] overflow-hidden bg-[#111016] p-6 text-white sm:min-h-[390px] sm:p-8"><div className="absolute right-10 top-10 h-52 w-52 rounded-full border border-white/15" /><div className={`absolute right-24 top-24 h-20 w-20 rounded-full blur-2xl transition-colors duration-500 ${capabilities[open]?.tone ?? 'bg-primary'}`} /><div className="relative flex h-full flex-col justify-between"><div className="flex justify-between font-mono text-[9px] uppercase tracking-[.2em] text-white/50"><span>Active discipline</span><span>{capabilities[open]?.number ?? '—'}</span></div><div><p className="font-display text-4xl font-semibold sm:text-6xl">{capabilities[open]?.title}</p><p className="mt-4 max-w-sm text-sm leading-6 text-white/55">{capabilities[open]?.text}</p></div></div></div></div></div></section>
}

export function CreativeTechnologyExperience() {
  return <section className="border-b border-border py-24 sm:py-32"><div className="mx-auto grid max-w-[1500px] gap-10 px-4 sm:grid-cols-2 sm:px-8 lg:px-12"><div className="bg-[#f0ece6] p-8 text-[#17151b] sm:p-12"><p className="font-mono text-[10px] uppercase tracking-[.3em] text-[#8d46d8]">03 / Creative</p><h2 className="mt-20 max-w-sm font-display text-4xl font-semibold leading-tight sm:text-6xl">Ideas with a point of view.</h2><p className="mt-6 max-w-sm text-sm leading-7 text-black/60">Brand identities, graphic design, photography, videography and content made to give businesses a distinct presence.</p></div><div className="bg-[#14121b] p-8 text-white sm:p-12"><p className="font-mono text-[10px] uppercase tracking-[.3em] text-orange-300">Digital / Technology</p><div className="mt-20 border border-white/15 bg-black/20 p-5 font-mono text-[10px] text-white/60"><div className="mb-6 flex justify-between border-b border-white/10 pb-3"><span>CONCEPTUAL SYSTEM</span><span className="text-emerald-300">ONLINE</span></div><div className="space-y-3"><div className="h-2 w-4/5 bg-white/20" /><div className="h-2 w-3/5 bg-orange-200/70" /><div className="h-2 w-2/3 bg-primary/70" /><div className="mt-7 grid grid-cols-3 gap-2"><span className="h-12 border border-white/10" /><span className="h-12 border border-white/10" /><span className="h-12 border border-white/10" /></div></div></div><p className="mt-6 max-w-sm text-sm leading-7 text-white/55">Websites, software, automation and AI concepts that make ambitious businesses easier to experience and operate.</p></div></div></section>
}

export function WorkExperience() {
  return <section id="work" className="border-b border-border py-24 sm:py-32"><div className="mx-auto max-w-[1500px] px-4 sm:px-8 lg:px-12"><div className="mb-12 flex items-end justify-between"><div><p className="mb-4 font-mono text-[10px] uppercase tracking-[.3em] text-primary">04 / Selected work</p><h2 className="font-display text-4xl font-semibold tracking-tight sm:text-7xl">Real clients.<br /><span className="text-foreground/40">No placeholders.</span></h2></div><Link href="/portfolio" className="hidden items-center gap-2 text-sm font-semibold sm:flex">View all work <ArrowUpRight className="h-4 w-4" /></Link></div><div className="divide-y divide-border border-y border-border">{projects.map((project, i) => <Link key={project.title} href="/case-studies" className="group grid gap-4 py-7 transition-colors hover:bg-card sm:grid-cols-[4rem_1fr_1fr_auto] sm:items-center sm:px-4"><span className="font-mono text-xs text-primary">{String(i + 1).padStart(2, '0')}</span><div><h3 className="font-display text-2xl font-semibold">{project.title}</h3><p className="mt-1 text-xs uppercase tracking-[.16em] text-muted-foreground">{project.services.join(' / ')}</p></div><p className="max-w-sm text-sm leading-6 text-muted-foreground">{project.description}</p><div className="flex items-center gap-3 text-xs font-semibold">Visual material coming soon <ArrowUpRight className="h-4 w-4 transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" /></div></Link>)}</div></div></section>
}

export function AVExperience() {
  const rows = ['AUDIO', 'VIDEO', 'CAMERAS', 'STREAM', 'LED', 'PROJECTION', 'TECHNICAL']
  return <section id="experience" className="overflow-hidden bg-[#08070b] py-24 text-white sm:py-36"><div className="mx-auto max-w-[1500px] px-4 sm:px-8 lg:px-12"><div className="mb-12 flex items-end justify-between gap-6"><div><p className="mb-4 font-mono text-[10px] uppercase tracking-[.3em] text-orange-300">05 / VisionVerve Live / Visualisation</p><h2 className="font-display text-5xl font-semibold sm:text-8xl">The show is<br /><span className="text-orange-300">the system.</span></h2></div><span className="hidden border border-orange-200/30 px-3 py-2 font-mono text-[9px] uppercase tracking-[.15em] text-orange-200 sm:block">Simulation — not a proprietary product</span></div><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><div className="border-y border-white/10">{rows.map((row, i) => <div key={row} className="flex items-center justify-between border-b border-white/10 py-4 last:border-0"><span className="font-mono text-xs tracking-[.18em] text-white/65">{row}</span><span className="flex items-center gap-2 font-mono text-[9px] text-orange-200"><i className="h-1.5 w-1.5 rounded-full bg-orange-300" />{i % 2 ? 'LIVE' : 'ACTIVE'}</span></div>)}</div><div className="border border-white/15 bg-white/[.03] p-5 sm:p-8"><div className="mb-6 flex justify-between border-b border-white/10 pb-4 font-mono text-[9px] uppercase tracking-[.18em] text-white/45"><span>Production control / 001</span><span className="text-emerald-300">System active</span></div><div className="grid gap-3 sm:grid-cols-3"><div className="border border-white/10 p-4"><p className="font-mono text-[9px] text-white/40">AUDIO</p><div className="mt-6 flex h-12 items-end gap-1">{[3, 6, 9, 5, 11, 7, 4, 10, 8, 5].map((n, i) => <motion.span key={i} className="flex-1 bg-orange-300/80" animate={{ height: [`${n * 5}%`, `${Math.min(94, n * 8)}%`, `${n * 5}%`] }} transition={{ duration: 1.4, repeat: Infinity, delay: i * .06 }} />)}</div></div><div className="border border-white/10 p-4"><p className="font-mono text-[9px] text-white/40">CAMERAS</p><div className="mt-6 aspect-video bg-gradient-to-br from-orange-200/30 via-primary/20 to-black" /><p className="mt-3 font-mono text-[9px] text-orange-200">CAM 01 / READY</p></div><div className="border border-white/10 p-4"><p className="font-mono text-[9px] text-white/40">ROUTING</p><div className="mt-6 space-y-3">{['LED WALL', 'STREAM', 'PROJECTION'].map((item) => <div key={item} className="flex items-center gap-2 font-mono text-[9px] text-white/60"><span className="h-px flex-1 bg-orange-200/50" /><span>{item}</span></div>)}</div></div></div><div className="mt-4 flex items-center justify-between border-t border-white/10 pt-4 font-mono text-[9px] uppercase tracking-[.18em] text-white/40"><span>Production timeline / 18:42</span><span>Signal locked</span></div></div></div></div></section>
}

export function ProcessAboutContact() {
  return <><section className="border-b border-border py-24 sm:py-32"><div className="mx-auto grid max-w-[1500px] gap-12 px-4 sm:grid-cols-[.75fr_1.25fr] sm:px-8 lg:px-12"><div><p className="mb-4 font-mono text-[10px] uppercase tracking-[.3em] text-primary">06 / How we work</p><h2 className="font-display text-4xl font-semibold sm:text-6xl">Thoughtful from first idea to final cue.</h2></div><div className="divide-y divide-border border-y border-border">{process.map(([number, title, text]) => <div key={number} className="grid grid-cols-[3rem_1fr] gap-4 py-5"><span className="font-mono text-xs text-primary">{number}</span><div><h3 className="font-display text-xl font-semibold">{title}</h3><p className="mt-1 text-sm text-muted-foreground">{text}</p></div></div>)}</div></div></section><section id="about" className="border-b border-border bg-[#f0ece6] py-24 text-[#17151b] sm:py-32"><div className="mx-auto grid max-w-[1500px] gap-10 px-4 sm:grid-cols-[1.1fr_.9fr] sm:px-8 lg:px-12"><div><p className="mb-4 font-mono text-[10px] uppercase tracking-[.3em] text-[#8d46d8]">07 / About VisionVerve</p><h2 className="font-display text-4xl font-semibold leading-tight sm:text-7xl">Cape Town-built.<br />Creative by nature.<br />Technical by choice.</h2></div><div className="self-end"><p className="max-w-md text-sm leading-7 text-black/60">Founded in 2024, VisionVerve brings creative thinking, technology, audiovisual production and live experiences together under one roof.</p><Link href="/about" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold">Meet the team <ArrowUpRight className="h-4 w-4" /></Link></div></div></section><section id="contact" className="border-b border-border py-24 sm:py-36"><div className="mx-auto flex max-w-[1500px] flex-col justify-between gap-10 px-4 sm:flex-row sm:items-end sm:px-8 lg:px-12"><div><p className="mb-4 font-mono text-[10px] uppercase tracking-[.3em] text-primary">08 / Start a project</p><h2 className="max-w-3xl font-display text-5xl font-semibold leading-[.95] tracking-tight sm:text-8xl">Have an idea?<br /><span className="text-gradient">Let&apos;s create it.</span></h2></div><div><Link href="/contact" className="group inline-flex items-center gap-3 border-b border-foreground/50 pb-3 text-sm font-semibold transition-colors hover:border-primary hover:text-primary">Contact VisionVerve <ArrowUpRight className="h-4 w-4 transition-transform group-hover:-translate-y-1 group-hover:translate-x-1" /></Link><a href="mailto:visionvervetech@gmail.com" className="mt-6 flex items-center gap-2 text-sm text-muted-foreground"><Mail className="h-4 w-4" />visionvervetech@gmail.com</a></div></div></section></>
}

export function HomeExperience() { return <main><HomeHero /><CapabilityExperience /><CreativeTechnologyExperience /><WorkExperience /><AVExperience /><ProcessAboutContact /></main> }
